---
# tasks file for myapache
- name: "Installing the Web Server(httpd)"
  package:
          name: httpd
          state: present
- name: "copy data to the directory"
  template:
          src: index.html.j2
          dest: /var/www/html/index.html
  register: x
- name: "Start the service"
  service:
          name: httpd
          state: restarted
          enabled: yes
  when: x.changed == true
